### ISSUE TITLE
Do research on previously established social media campaigns that have similar goals to that of the 100k initiative

### ISSUE THREAD

**Issue by catherine923** [promazo/100K-Mentors-PR-Students#12]
have an comparative understanding of what past campaigns have been and what it takes to build a similar campaign

**Comment by aflies1** [comment]
Done = Document that lays out an overview of past campaigns, list what you thought worked well, how we could potentially use some of the same ideas, other findings/thoughts on each.

**Comment by catherine923** [comment]
https://docs.google.com/document/d/1Fg_bcGdbEfPjtk2Bd3REuO1hEwpzOYM0KG4ALzFC6kM/edit

**Comment by catherine923** [comment]
https://docs.google.com/document/d/1Fg_bcGdbEfPjtk2Bd3REuO1hEwpzOYM0KG4ALzFC6kM/edit

I made more updates as well as added a bit of a rough layout for what a plan for social might look like. I plan to speak with Rachel on Wednesday after our meeting and speak with her on what her suggestions might be
