### ISSUE TITLE
Research and compile a list of colleges and universities to target in our first round of outreach

### ISSUE THREAD

**Issue by lexieabrahamian** [promazo/100K-Mentors-PR-Students#13]
- Decide how many total colleges and universities will be included in the first round of outreach 

- Compile a list of HBCUs

- Compile a list of other state colleges/universities, both large and small

- Narrow the list of colleges down to the number designated previously as the first round of outreach

**Done** = compile the list of all these colleges into a well-organized spreadsheet that we will use to keep track of progress with each university and communication with specific contacts at each one. 

-~40 of the largest/most prominent HBCUs
-5-6 major universities from each of the 5 regions of the US
-From the list select 4-5 HBCUs to go after, 2 major universities from each region to go after.
-Give a quick explanation in this card as to why we will begin with going after those Universities first. Send to Adam for review and set up a time to discuss.

**Comment by aflies1** [comment]
Done= Spreadsheet with list of all HBCU's, 5-6 major universities from each of the 5 regions of the US. From the list select 4-5 HBCUs to go after, 2 major universities from each region to go after. Give a quick explanation in this card as to why we will begin with going after those Universities first. Send to Adam for review and set up a time to discuss.

**Comment by lexieabrahamian** [comment]
[https://app.zenhub.com/files/273752984/b79366c4-3e3b-441b-845c-1470d90f1156/download](https://app.zenhub.com/files/273752984/b79366c4-3e3b-441b-845c-1470d90f1156/download)
