### ISSUE TITLE
Secure student endorsements

### ISSUE THREAD

**Issue by catherine923** [promazo/100K-Mentors-PR-Students#15]
both previous students who have had previous success with Promazo’s program as well as students who have a large social media base (on platforms such as twitter or linkedin) as well have morals and drive that line up with that of the campaigns

**Comment by aflies1** [comment]
Try and list what each of these tasks would look like. 1. Secure list of past ProMazo students who are now in the corporate/business/nonprofit world (you could go deeper as this would need to be assigned to Adam, "Secure list of past students from Adam.) 2. Create a list of target universities, then identify social media campus influencers on those campuses (Would want to talk with Lexie on which universities she is targeting)

Within this task or if you wanted to break them in smaller tasks what will we need to secure "student endorsements" next? 1. Create messaging, pitch, and ask? 2.What materials will that secured influencer need from us? 3.What will the potential timing look like? When will we want them to promote?

**Comment by aflies1** [comment]
- [x] check
