### ISSUE TITLE
For each college or university on the list, identify the target office/department and a list of possible contacts to email our initial pitch to

### ISSUE THREAD

**Issue by lexieabrahamian** [promazo/100K-Mentors-PR-Students#16]
- For HBCUs, identify the career center or similar advising/counseling office, as Black students are already underrepresented in colleges all over the country and will make up most, if not all, students at HBCUs. 

- Using the university's website identify an individual with the title of associate director, assistant director, or director. An example from the University of Washington’s career center is the Associate Director of Employer & Student Engagement. 

- For other state colleges and universities, identify the office or department designed to support underrepresented students such as students of color, Indigenous students, first-gen students, disabled students, LGBTQ+ students, immigrant/refugee/undocumented students and more. At many universities and colleges, this office is called something similar to the Office of Minority Affairs and Diversity or Office of Diversity and Inclusion, etc. Within these departments, there will likely be many smaller offices that work with more specific groups of students, such as CAMP, which works specifically with Latinx students who are children of migrant workers. 

- Identify a vice president of the department or directors for specific smaller branches of the larger department. For example, if we don’t receive anything from the highest ranking individual, we can contact the director of their advising and student support offices, such as the Educational Opportunity Program. 

- It will be helpful to document the names of several individuals within each university to ensure that we reach as many students at each school as possible.

**Done** = compiling the contacts for each university in the target universities spreadsheet (the original one).

**Comment by aflies1** [comment]
This is great! I'd add in where this information is going to live. More than likely we can build upon the original spreadsheet of target Universities.
