### ISSUE TITLE
Craft messaging for future video call meetings with any of the contacts we reach out to

### ISSUE THREAD

**Issue by lexieabrahamian** [promazo/100K-Mentors-PR-Students#18]
- Questions to answer with our messaging: 

- What is the 100k Mentors Initiative? 

- What will it do for students? What is the impact, specifically for underrepresented students and 

- What specific action are we asking them to take to connect students with our mentorship initiative?

- Adam will be in all university meetings for our team. 

**Done** =  a completed document with FAQs, and a Pitch document for securing University buy in during a meeting.

**Comment by aflies1** [comment]
Great thinking here. Done= Document with FAQs, Pitch document for securing University buy in,

Adam will be in all university meetings with you.
