### ISSUE TITLE
Contact each target individual at each Univ. and update the spreadsheet to keep track of who we have contacted

### ISSUE THREAD

**Issue by lexieabrahamian** [promazo/100K-Mentors-PR-Students#19]
-In our spreadsheet, create a sort of checklist for every university and every contact to track which ones have been reached out to (“Done" or "X"), which contacts have responded, and whether that response was positive or negative (will it lead to further action?). 

-Go through each college/university and send our crafted email to each individual on our list. Keep track of completed emails and responses in the spreadsheet. 

**Done** = at least one (if not more than one) contact at each target university (our short list) has been reached out to over email and the "contacted" column of the spreadsheet shows each university as "Done".

**Comment by aflies1** [comment]
Could be added to the original target spreadsheet.
